
service: capstone-lambda-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'alpha'}
  profile: ${env:PROFILE}
  apiName: ${env:PROJECT_NAME}
  region: ap-south-1
  memorySize: 512
  timeout: 25
  endpointType: regional
  logs:
    restApi: true
    level: INFO
  deploymentBucket:
    blockPublicAccess: true
    name: ${env:CODE_DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 3

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

package:
  individually: true
  patterns:
    - '!.venv/**'
    - '!venv/**'
    - '!env_*'
    - '!.env*'
    - '!.git/**'
    - '!.idea/**'
    - '!__pycache__/**'
    - '!config/**'
    # - '!node_modules/**'
    - '!layers/**'
    - '!*.pyc'
    - '!static/**'
    - '!media/**'
    - '!db.sqlite3'
    - '!*.ipynb'

plugins:
  - serverless-offline